version: "3.7"

services:
  # APPS
  gateway:
    build:
      context: ./apps/gateway
      target: development
    ports:
      - ${GATEWAY_PORT-3000}:3000
    volumes:
      - ./apps/gateway:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - auth-user
      - demand
      - order
      - payment
      - restaurant
      - shipping

  pwa:
    build:
      context: ./apps/pwa
      target: development
    ports:
      - ${PWA_PORT-3001}:3000
    volumes:
      - ./apps/pwa:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - gateway

  admin-dashboard:
    build:
      context: ./apps/admin-dashboard
      target: development
    ports:
      - ${ADMIN_DASHBOARD_PORT-3002}:3000
    volumes:
      - ./apps/admin-dashboard:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - gateway

  # SERVICES
  auth-user:
    build:
      context: ./services/auth-user-service
      target: development
    ports:
      - ${AUTH_PORT-4000}:3000
    volumes:
      - ./services/auth-user-service:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - auth-user-db

  demand:
    build:
      context: ./services/demand-service
      target: development
    ports:
      - ${DEMAND_PORT-4001}:3000
    volumes:
      - ./services/demand-service:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - demand-db

  order:
    build:
      context: ./services/order-service
      target: development
    ports:
      - ${ORDER_PORT-4002}:3000
    volumes:
      - ./services/order-service:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - order-db

  payment:
    build:
      context: ./services/payment-service
      target: development
    ports:
      - ${PAYMENT_PORT-4003}:3000
    volumes:
      - ./services/payment-service:/home/node/app
      - /home/node/app/node_modules

  restaurant:
    build:
      context: ./services/restaurant-service
      target: development
    ports:
      - ${RESTAURANT_PORT-4004}:3000
    volumes:
      - ./services/restaurant-service:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - restaurant-db

  shipping:
    build:
      context: ./services/shipping-service
      target: development
    ports:
      - ${SHIPPING_PORT-4005}:3000
    volumes:
      - ./services/shipping-service:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - shipping-db

  # DATABASES
  auth-user-db:
    image: postgres:15-alpine
    container_name: auth-user-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth-user-db
    ports:
      - ${AUTH_USER_DB_PORT-5432}:5432
    volumes:
      - auth-user-db:/var/lib/postgresql/data
  demand-db:
    image: postgres:15-alpine
    container_name: demand-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: demand-db
    ports:
      - ${DEMAND_DB_PORT-5433}:5432
    volumes:
      - demand-db:/var/lib/postgresql/data
  order-db:
    image: postgres:15-alpine
    container_name: order-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: order-db
    ports:
      - ${ORDER_DB_PORT-5434}:5432
    volumes:
      - order-db:/var/lib/postgresql/data
  restaurant-db:
    image: postgres:15-alpine
    container_name: restaurant-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: restaurant-db
    ports:
      - ${RESTAURANT_DB_PORT-5435}:5432
    volumes:
      - restaurant-db:/var/lib/postgresql/data
  shipping-db:
    image: postgres:15-alpine
    container_name: shipping-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: shipping-db
    ports:
      - ${SHIPPING_DB_PORT-5436}:5432
    volumes:
      - shipping-db:/var/lib/postgresql/data
  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - auth-user-db
      - demand-db
      - order-db
      - restaurant-db
      - shipping-db
    ports:
      - "8080:8080"

volumes:
  auth-user-db:
  demand-db:
  order-db:
  restaurant-db:
  shipping-db: