version: '3.8'

services:
# DATABASES
  auth-user-db:
    image: postgres:15-alpine
    container_name: auth-user-db
    restart: always
  demand-db:
    image: postgres:15-alpine
    container_name: demand-db
    restart: always
  order-db:
    image: postgres:15-alpine
    container_name: order-db
    restart: always
  restaurant-db:
    image: postgres:15-alpine
    container_name: restaurant-db
    restart: always
  shipping-db:
    image: postgres:15-alpine
    container_name: shipping-db
    restart: always

# SERVICES
  admin-website:
    container_name: admin-website
    build:
      context: ./admin-website
    restart: unless-stopped

  pwa:
    container_name: pwa
    build:
      context: ./pwa
    restart: unless-stopped

  auth-user-service:
    container_name: auth-user-service
    build:
      context: ./auth-user-service
    restart: unless-stopped

  demand-service:
    container_name: demand-service
    build:
      context: ./demand-service
    restart: unless-stopped

  order-service:
    container_name: order-service
    build:
      context: ./order-service
    restart: unless-stopped

  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
    restart: unless-stopped

  restaurant-service:
    container_name: restaurant-service
    build:
      context: ./restaurant-service
    restart: unless-stopped

  shipping-service:
    container_name: shipping-service
    build:
      context: ./shipping-service
    restart: unless-stopped
