apiVersion: v1
kind: Service
metadata:
  name: gys-main-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_gys-rg_gys-akc_francecentral
    service.beta.kubernetes.io/azure-load-balancer-ipv4: 20.111.43.31
spec:
  loadBalancerIP: 20.111.43.31
  selector:
    app: gys-main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer