apiVersion: apps/v1
kind: Deployment
metadata:
  name: gys-payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gys-payment
  template:
    metadata:
      labels:
        app: gys-payment
    spec:
      containers:
        - name: gys-payment
          image: gysacr.azurecr.io/payment-service:latest
          ports:
            - containerPort: 4003
          env:
            - name: APP_PORT
              value: "4003"
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: PAYMENT_DATABASE_URL
                  name: gys-configmap
            - name: STRIPE_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: STRIPE_SECRET_KEY
                  name: gys-configmap
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                  configMapKeyRef:
                    key: STRIPE_PUBLIC_KEY
                    name: gys-configmap